### ISSUE TITLE
Running .NET Core SqlPackage from a Linux Host against a Windows-based SQL Server results in errors

### ISSUE THREAD

**Issue by pportnoy** [microsoft/DACExtensions#37]
I'm generating a `dacpac` file using `sqlpackage` running on Linux from a SQL Server database hosted on a SQL Server running on Windows.

Here's the syntax I'm using:
```
sqlpackage /Action:Extract /TargetFile:schema.dacpac /SourceServerName:servername.domain.com /SourceDatabaseName:test /SourceUser:deploytest /SourcePassword:VerySecurePassword /Diagnostics:True /p:Storage=Memory /p:ExtractReferencedServerScopedElements=False /p:ExtractUsageProperties=False /p:IgnoreUserLoginMappings=True
```

Both the SQL Server and database collations are `SQL_Latin1_General_CP1_CI_AS` (I've also tested with `Latin1_General_CP1_CI_AS`).

`sqlpackage` tool fails to generate the dacpac. Here's the highlight from the diagnostics log (full log is below):

```
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Tools.Schema.SchemaModel.ModelCollation' threw an exception. ---> System.ArgumentException: Collation (1033) is not supported on this computer.
```

It appears like there's a collation conflict... How can we fix it?

```
Connecting to database 'test' on server 'servername.domain.com'.
Microsoft.Data.Tools.Diagnostics.Tracer Information: 0 : 2020-02-19T20:55:00 : Initialized ModelSchema - elements 149
Microsoft.Data.Tools.Diagnostics.Tracer Information: 19 : 2020-02-19T20:55:00 : IsolatedStorageFile probe success
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : Logging Ambient Settings...
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : DatabaseLockTimeout: 60000
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : QueryTimeout: 60
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : LongRunningQueryTimeout: 0
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysRetryOnTransientFailure: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : ConnectionRetryHandler:
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : MaxDataReaderDegreeOfParallelism: 8
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : TraceRowCountFailure: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : TableProgressUpdateInterval: 300
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : UseOfflineDataReader: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : StreamBackingStoreForOfflineDataReading: File
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : ModelFilePath:
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : MasterReferenceFilePath:
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : DisableIndexesForDataPhase: True
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : ReliableDdlEnabled: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : ImportModelDatabase: True
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : SupportAlwaysEncrypted: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysEncryptedWizardMigration: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysEncryptedWizardPreserveTable: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysEncryptedWizardUseOnlineApproach: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysEncryptedWizardDowntimeInSeconds: 300
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysEncryptedWizardMaxDivergingIterations: 5
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysEncryptedWizardMaxIterations: 100
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : AlwaysEncryptedWizardMaxIterationDurationInDays: 3
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : SkipObjectTypeBlocking: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : DoNotSerializeQueryStoreSettings: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : LargeObjectHeapCompaction: False
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : LargeObjectHeapCompactionIntervalInSeconds: 30
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : ReferencePaths: System.String[]
Microsoft.Data.Tools.Diagnostics.Tracer Warning: 0 : 2020-02-19T20:55:00 : DeploymentContributorPaths: System.String[]
Extracting schema
Extracting schema from database
Microsoft.Data.Tools.Diagnostics.Tracer Verbose: 1 : 2020-02-19T20:55:00 : Entering ExtensionTypeLoader.LoadTypes().
Time elapsed 00:00:03.75
Microsoft.Data.Tools.Diagnostics.Tracer Error: 0 : 2020-02-19T20:55:04 : SqlPackage failed unexpectedly
 Exception: Microsoft.Data.Tools.Schema.Extensibility.ExtensibilityException: The extension type Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModelConstructor could not be instantiated. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Data.Tools.Schema.SchemaModel.ModelCollation' threw an exception. ---> System.ArgumentException: Collation (1033) is not supported on this computer.
   at Microsoft.Data.Tools.Schema.SchemaModel.ModelCollation..ctor(Int32 lcid, Boolean caseSensitive) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SchemaModel\ModelCollation.cs:line 146
   at Microsoft.Data.Tools.Schema.SchemaModel.ModelCollation..cctor() in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SchemaModel\ModelCollation.cs:line 96
   --- End of inner exception stack trace ---
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModelConstructor..ctor() in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SchemaModel\SqlSchemaModelConstructor.cs:line 90
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at Microsoft.Data.Tools.Schema.Extensibility.ExtensionTypeLoader.InstantiateType[T](Type type) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\Extensibility\ExtensionTypeLoader.cs:line 666
   --- End of inner exception stack trace ---
   at Microsoft.Data.Tools.Schema.Extensibility.ExtensionTypeLoader.InstantiateType[T](Type type) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\Extensibility\ExtensionTypeLoader.cs:line 679
   at Microsoft.Data.Tools.Schema.DatabaseSchemaProvider.GetServiceConstructor[TServiceConstructor]() in F:\B\16846\6200\Sources\Product\Source\SchemaSql\DatabaseSchemaProvider.cs:line 139
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineerImpl.CreateDataSchemaModel(SqlReverseEngineerConnectionContext context, ErrorManager errors, Boolean optimizeForQuery, Boolean isMsdb, ModelStorageType modelType, Boolean storeSourceCodePositionAnnotations) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SchemaModel\SqlReverseEngineerImpl.cs:line 3009
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineerImpl.CreateModel(SqlReverseEngineerConnectionContext context, ErrorManager errorManager, Boolean optimizeForQuery, Boolean isMsdb, ModelStorageType modelType, Boolean storeSourceCodePositionAnnotations) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SchemaModel\SqlReverseEngineerImpl.cs:line 2303
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineer.PopulateAll(SqlReverseEngineerConnectionContext context, ReverseEngineerOption option, ErrorManager errorManager, Boolean filterManagementScopedElements, SqlImportScope importScope, Boolean optimizeForQuery, ModelStorageType modelType) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SchemaModel\SqlReverseEngineer.cs:line 218
   at Microsoft.Data.Tools.Schema.SchemaModel.ReverseEngineerExtensionMethods.ImportDatabase(SqlReverseEngineer reverseEngineer, SqlReverseEngineerConnectionContext context, ReverseEngineerOption option, ErrorManager errorManager, Boolean filterManagementScopedElements, Boolean populateReferencedServerScopedElements, Boolean trimDanglingReferencesOnServerScopedElements, Boolean removeUnReferencedServerObjects, ModelStorageType modelStorageType, Boolean removeUnreferencedDbCredential) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SchemaModel\ReverseEngineerExtensionMethods.cs:line 196
   at Microsoft.SqlServer.Dac.ExtractOperation.<>c__DisplayClass14_0.<CreateReverseEngineerOperation>b__0(Object operation, CancellationToken token) in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\ExtractOperation.cs:line 179
   at Microsoft.SqlServer.Dac.Operation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context) in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\Operation.cs:line 72
   at Microsoft.SqlServer.Dac.ReportMessageOperation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context) in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\ReportMessageOperation.cs:line 44
   at Microsoft.SqlServer.Dac.OperationExtension.CompositeOperation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context) in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\IOperation.cs:line 63
   at Microsoft.SqlServer.Dac.ExtractOperation.<>c__DisplayClass21_0.<Microsoft.SqlServer.Dac.IOperation.Run>b__0() in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\ExtractOperation.cs:line 390
   at Microsoft.Data.Tools.Schema.Sql.Dac.OperationLogger.Capture(Action action) in F:\B\16846\6200\Sources\Product\Source\SchemaSql\Dac\Logging\OperationLogger.cs:line 49
   at Microsoft.SqlServer.Dac.OperationExtension.Execute(IOperation operation, DacLoggingContext loggingContext, CancellationToken cancellationToken) in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\IOperation.cs:line 26
   at Microsoft.SqlServer.Dac.DacServices.Extract(Func`1 streamGetter, String databaseName, String applicationName, Version applicationVersion, String applicationDescription, IEnumerable`1 tables, DacExtractOptions extractOptions, Nullable`1 cancellationToken, DacLoggingContext extractLoggingContext) in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\DacServices.cs:line 300
   at Microsoft.SqlServer.Dac.DacServices.Extract(String packageFileName, String databaseName, String applicationName, Version applicationVersion, String applicationDescription, IEnumerable`1 tables, DacExtractOptions extractOptions, Nullable`1 cancellationToken) in F:\B\16846\6200\Sources\Product\Source\DeploymentApi\DacServices.cs:line 234
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.DoExtractDacpacOperation(CommandLineArguments parsedArgs) in F:\B\16846\6200\Sources\Product\Source\SqlPackage\Program.cs:line 661
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.PerformAction(CommandLineArguments parsedArgs) in F:\B\16846\6200\Sources\Product\Source\SqlPackage\Program.cs:line 206
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.Run(String[] args) in F:\B\16846\6200\Sources\Product\Source\SqlPackage\Program.cs:line 156
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.Main(String[] args) in F:\B\16846\6200\Sources\Product\Source\SqlPackage\Program.cs:line 50
*** An unexpected failure occurred: The extension type Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModelConstructor could not be instantiated..
```

**Comment by pportnoy** [comment]
Never mind. This error occurs when `sqlpackage` is **not** executed as `sudo`. Very confusing error but it's a non-issue.
